//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 02:01:34 PM IST 
//


package de.hybris.platform.ndcfacades.ndc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * BINARY ENCODED MEDIA representation.
 * 
 * <p>Java class for Base64MediaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Base64MediaType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iata.org/IATA/EDIST/2017.1}AssociatedObjectBaseType">
 *       &lt;sequence>
 *         &lt;element name="EncodedValue">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                 &lt;attGroup ref="{http://www.iata.org/IATA/EDIST/2017.1}ObjAssociationAttrGroup"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Descriptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Description" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}LinkToMediaDescription"/>
 *                             &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaMarkupDescription"/>
 *                             &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaPlainDescription"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceEncoding" type="{http://www.iata.org/IATA/EDIST/2017.1}ServiceEncodingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Base64MediaType", propOrder = {
    "encodedValue",
    "descriptions",
    "serviceEncoding"
})
public class Base64MediaType
    extends AssociatedObjectBaseType
{

    @XmlElement(name = "EncodedValue", required = true)
    protected Base64MediaType.EncodedValue encodedValue;
    @XmlElement(name = "Descriptions")
    protected Base64MediaType.Descriptions descriptions;
    @XmlElement(name = "ServiceEncoding")
    protected ServiceEncodingType serviceEncoding;

    /**
     * Gets the value of the encodedValue property.
     * 
     * @return
     *     possible object is
     *     {@link Base64MediaType.EncodedValue }
     *     
     */
    public Base64MediaType.EncodedValue getEncodedValue() {
        return encodedValue;
    }

    /**
     * Sets the value of the encodedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64MediaType.EncodedValue }
     *     
     */
    public void setEncodedValue(Base64MediaType.EncodedValue value) {
        this.encodedValue = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link Base64MediaType.Descriptions }
     *     
     */
    public Base64MediaType.Descriptions getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64MediaType.Descriptions }
     *     
     */
    public void setDescriptions(Base64MediaType.Descriptions value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the serviceEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceEncodingType }
     *     
     */
    public ServiceEncodingType getServiceEncoding() {
        return serviceEncoding;
    }

    /**
     * Sets the value of the serviceEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceEncodingType }
     *     
     */
    public void setServiceEncoding(ServiceEncodingType value) {
        this.serviceEncoding = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Description" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}LinkToMediaDescription"/>
     *                   &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaMarkupDescription"/>
     *                   &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaPlainDescription"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description"
    })
    public static class Descriptions {

        @XmlElement(name = "Description", required = true)
        protected List<Base64MediaType.Descriptions.Description> description;

        /**
         * Gets the value of the description property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the description property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Base64MediaType.Descriptions.Description }
         * 
         * 
         */
        public List<Base64MediaType.Descriptions.Description> getDescription() {
            if (description == null) {
                description = new ArrayList<Base64MediaType.Descriptions.Description>();
            }
            return this.description;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}LinkToMediaDescription"/>
         *         &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaMarkupDescription"/>
         *         &lt;element ref="{http://www.iata.org/IATA/EDIST/2017.1}MediaPlainDescription"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "linkToMediaDescription",
            "mediaMarkupDescription",
            "mediaPlainDescription"
        })
        public static class Description {

            @XmlElement(name = "LinkToMediaDescription", required = true)
            protected UriContextType linkToMediaDescription;
            @XmlElement(name = "MediaMarkupDescription", required = true)
            protected MediaMarkupDescType mediaMarkupDescription;
            @XmlElement(name = "MediaPlainDescription", required = true)
            protected MediaPlainDescType mediaPlainDescription;

            /**
             * Gets the value of the linkToMediaDescription property.
             * 
             * @return
             *     possible object is
             *     {@link UriContextType }
             *     
             */
            public UriContextType getLinkToMediaDescription() {
                return linkToMediaDescription;
            }

            /**
             * Sets the value of the linkToMediaDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link UriContextType }
             *     
             */
            public void setLinkToMediaDescription(UriContextType value) {
                this.linkToMediaDescription = value;
            }

            /**
             * Gets the value of the mediaMarkupDescription property.
             * 
             * @return
             *     possible object is
             *     {@link MediaMarkupDescType }
             *     
             */
            public MediaMarkupDescType getMediaMarkupDescription() {
                return mediaMarkupDescription;
            }

            /**
             * Sets the value of the mediaMarkupDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link MediaMarkupDescType }
             *     
             */
            public void setMediaMarkupDescription(MediaMarkupDescType value) {
                this.mediaMarkupDescription = value;
            }

            /**
             * Gets the value of the mediaPlainDescription property.
             * 
             * @return
             *     possible object is
             *     {@link MediaPlainDescType }
             *     
             */
            public MediaPlainDescType getMediaPlainDescription() {
                return mediaPlainDescription;
            }

            /**
             * Sets the value of the mediaPlainDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link MediaPlainDescType }
             *     
             */
            public void setMediaPlainDescription(MediaPlainDescType value) {
                this.mediaPlainDescription = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *       &lt;attGroup ref="{http://www.iata.org/IATA/EDIST/2017.1}ObjAssociationAttrGroup"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EncodedValue {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "refs")
        @XmlIDREF
        protected List<Object> refs;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the refs property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the refs property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRefs().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getRefs() {
            if (refs == null) {
                refs = new ArrayList<Object>();
            }
            return this.refs;
        }

    }

}
