//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.07 at 04:46:04 PM GMT 
//


package de.hybris.platform.ndcfacades.ndc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A base type for an Object with Instance Associations.
 * 
 * <p>Java class for AssociatedObjectBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedObjectBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.iata.org/IATA/EDIST}ObjAssociationAttrGroup"/>
 *       &lt;attribute name="ApproxInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="RefundAllInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ExemptAllInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="AllGuaranteeInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DisclosureInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="BrowserInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedObjectBaseType")
@XmlSeeAlso({
    de.hybris.platform.ndcfacades.ndc.ShopProductRQ.Query.Locations.class,
    de.hybris.platform.ndcfacades.ndc.ShopProductRQ.Query.class,
    de.hybris.platform.ndcfacades.ndc.OrderChangeNotif.Query.Amendments.Amendment.OfferItem.class,
    de.hybris.platform.ndcfacades.ndc.BagChargeReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.BagChargeReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.BagChargeResParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.BagChargeResParamsType.Pricing.FeeExemption.class,
    AirDocCancelResProcessType.class,
    ShopProductResProcessType.class,
    de.hybris.platform.ndcfacades.ndc.InvGuaranteeRQ.Query.Qualifiers.Locations.class,
    de.hybris.platform.ndcfacades.ndc.OrderViewRS.Response.Amendments.Amendment.OfferItem.class,
    CustInputResProcessType.class,
    de.hybris.platform.ndcfacades.ndc.SrvListResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.SrvListReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.SrvListReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.BagAllowResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.BagAllowReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.BagAllowReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.AirShopReqAttributeQueryType.OriginDestination.class,
    de.hybris.platform.ndcfacades.ndc.AirShopReqAffinityQueryType.OriginDestination.class,
    InvGuarResProcessType.class,
    de.hybris.platform.ndcfacades.ndc.FltPriceReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.FltPriceReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.FltPriceResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.SrvPriceResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.SrvPriceReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.SrvPriceReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.BagListResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.BagListReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.BagListReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.AirShopReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.AirShopReqParamsType.Pricing.FeeExemption.class,
    MediaMarkupDescType.class,
    de.hybris.platform.ndcfacades.ndc.SeatAvailResParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.SeatAvailReqParamsType.ServiceFilters.class,
    de.hybris.platform.ndcfacades.ndc.SeatAvailReqParamsType.Pricing.FeeExemption.class,
    de.hybris.platform.ndcfacades.ndc.ShopProductResParamsType.Pricing.FeeExemption.class,
    OrdChangeAlertsType.class,
    OrderListAlertsType.class,
    HexMediaType.class,
    de.hybris.platform.ndcfacades.ndc.AirShopResParamsType.Pricing.FeeExemption.class,
    ItinReshopAlertsType.class,
    OrdRetrieveAlertsType.class,
    OrdCreateAlertsType.class,
    Base64MediaType.class
})
public class AssociatedObjectBaseType {

    @XmlAttribute(name = "ApproxInd")
    protected Boolean approxInd;
    @XmlAttribute(name = "RefundAllInd")
    protected Boolean refundAllInd;
    @XmlAttribute(name = "ExemptAllInd")
    protected Boolean exemptAllInd;
    @XmlAttribute(name = "AllGuaranteeInd")
    protected Boolean allGuaranteeInd;
    @XmlAttribute(name = "DisclosureInd")
    protected Boolean disclosureInd;
    @XmlAttribute(name = "BrowserInd")
    protected Boolean browserInd;
    @XmlAttribute(name = "refs")
    @XmlIDREF
    protected List<Object> refs;

    /**
     * Gets the value of the approxInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApproxInd() {
        return approxInd;
    }

    /**
     * Sets the value of the approxInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApproxInd(Boolean value) {
        this.approxInd = value;
    }

    /**
     * Gets the value of the refundAllInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefundAllInd() {
        return refundAllInd;
    }

    /**
     * Sets the value of the refundAllInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefundAllInd(Boolean value) {
        this.refundAllInd = value;
    }

    /**
     * Gets the value of the exemptAllInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExemptAllInd() {
        return exemptAllInd;
    }

    /**
     * Sets the value of the exemptAllInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExemptAllInd(Boolean value) {
        this.exemptAllInd = value;
    }

    /**
     * Gets the value of the allGuaranteeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllGuaranteeInd() {
        return allGuaranteeInd;
    }

    /**
     * Sets the value of the allGuaranteeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllGuaranteeInd(Boolean value) {
        this.allGuaranteeInd = value;
    }

    /**
     * Gets the value of the disclosureInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisclosureInd() {
        return disclosureInd;
    }

    /**
     * Sets the value of the disclosureInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisclosureInd(Boolean value) {
        this.disclosureInd = value;
    }

    /**
     * Gets the value of the browserInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBrowserInd() {
        return browserInd;
    }

    /**
     * Sets the value of the browserInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBrowserInd(Boolean value) {
        this.browserInd = value;
    }

    /**
     * Gets the value of the refs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getRefs() {
        if (refs == null) {
            refs = new ArrayList<Object>();
        }
        return this.refs;
    }

}
